version: '3.8'

services:
  mariadb:
    image: mariadb:latest
    container_name: mariadb-server
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: your_root_password
      MYSQL_DATABASE: lipu
      MYSQL_USER: kawa
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - mariadb_data:/var/lib/mysql

volumes:
  mariadb_data:
